BBS.Web/Models/CardRequestViewModel.cs
using BBS.Models.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BBS.Web.Models
{
    public class CardRequestViewModel
    {
        [Required]
        [Display(Name = "Company Name")]
        public string CompanyName { get; set; }
        [Required]
        [Display(Name = "Address")]
        public string CompanyAddress { get; set; }
        [Required]
        [Display(Name = "Phone")]
        public string CompanyPhone { get; set; }
        [Display(Name = "City")]
        public City City { get; set; }

        public static implicit operator CardRequest(CardRequestViewModel cardRequestViewModel)
        {
            return new CardRequest
            {
                CompanyPhone = cardRequestViewModel.CompanyPhone,
                CompanyName = cardRequestViewModel.CompanyName,
                CompanyAddress = cardRequestViewModel.CompanyAddress,
                City = cardRequestViewModel.City,
                CardId = cardRequestViewModel.City.Id,
                CardRequestStatus = CardRequestStatus.New,
                CreatedAt = DateTime.Now,
            };
        }

    }
}

BBS.Web/Models/UpdateRequestViewModel.cs
using BBS.Models.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BBS.Web.Models
{
    public class UpdateRequestViewModel
    {
        public CardRequest CardRequest { get; set; }
        public City City { get; set; }
        public CardRequestHistory CardRequestHistory { get; set; }
        public List<CardRequestHistory> CardRequestHistories { get; set; }
    }
}

BBS.Web/Areas/Administration/Controllers/CardRequestController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BBS.DAL.Repositories;
using BBS.Interfaces.Services;
using BBS.Models.Models;
using BBS.Web.Areas.Administration.Constants;
using BBS.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace BBS.Web.Areas.Administration.Controllers
{
    [Area(AdministratorArea.Name)]
    public class CardRequestController : Controller
    {
        private readonly ICardRequestService _cardRequestService;
        private readonly ICardRequestHistoryService _cardRequestHistoryService;
        private readonly ICityRepository _cityRepository;
        private readonly ICardService _cardService;
        private readonly IBankAccountService _bankAccountService;

        public CardRequestController(ICardRequestService cardRequestService, 
                                     ICardRequestHistoryService cardRequestHistoryService, 
                                     ICityRepository cityRepository,
                                     ICardService cardService,
                                     IBankAccountService bankAccountService)
        {
            _bankAccountService = bankAccountService;
            _cardService = cardService;
            _cityRepository = cityRepository;
            _cardRequestHistoryService = cardRequestHistoryService;
            _cardRequestService = cardRequestService; 
        }
        public async Task<IActionResult> Index()
        {
            var cardRequests = (await _cardRequestService.GetAllIncludes()).ToList();

            return View(cardRequests);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateRequest(int id)
        {
            var updateRequestViewModel = new UpdateRequestViewModel();
            updateRequestViewModel.CardRequest = (await _cardRequestService.GetByIdIncludes(id));
            updateRequestViewModel.City = await _cityRepository.GetByIdAsync(updateRequestViewModel.CardRequest.CityId);
            updateRequestViewModel.CardRequestHistories = await _cardRequestHistoryService.GetAllByRequestIdIncludes(id);
            return View(updateRequestViewModel);
        }
        public async Task<IActionResult> Accept(int id)
        {
            var cardRequest = await _cardRequestService.GetById(id);
            cardRequest.CardRequestStatus = CardRequestStatus.Accepted;
            await _cardRequestService.Update(cardRequest);
            await _cardRequestHistoryService.MakeHistory(cardRequest.UserId);
            var accaunt = await _bankAccountService.GetUserAccounts(cardRequest.UserId);
            await _cardService.GenerateCard(accaunt.Where(x=>x.UserId == cardRequest.UserId).FirstOrDefault(), BBS.Core.Helpers.CardHelper.CardTypes.typeDeluxe);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Decline(int id)
        {
            var cardRequest = await _cardRequestService.GetById(id);
            cardRequest.CardRequestStatus = BBS.Models.Models.CardRequestStatus.Declined;
            await _cardRequestService.Update(cardRequest);
            await _cardRequestHistoryService.MakeHistory(cardRequest.UserId);
            return RedirectToAction(nameof(Index));
        }


    }
}

BBS.Web/Areas/Administration/Views/CardRequest/Index.cshtml
@model IEnumerable<BBS.Models.Models.CardRequest>

@{
    ViewData["Title"] = "Index";
}

<h1 class="d-flex justify-content-center opacity-90 text-muted mt-4">Custom card requests</h1>

<div class="row">
    <div class="col-sm-12" style="border: 1px solid black; padding: 10px; margin-bottom: 10px;">
        De luxe Salary Card
    </div>
</div>

<table class="table table-bordered" >
    <thead class="thead-dark">
        <tr>
            <th>
                Request Date
            </th>
            <th>
                Name
            </th>
            <th>
                Company Name
            </th>
            <th>
                Company Address
            </th>
            <th>
                Company Phone
            </th>
            <th>
                Request Status
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @item.CreatedAt.ToShortDateString()
            </td>

            <td>
                @item.User.FirstName @item.User.LatsName
            </td>

            <td>
                @item.CompanyName
            </td>
            <td>
                @item.CompanyAddress
            </td>
            <td>
                @item.CompanyPhone
            </td>
            <td>
                @item.CardRequestStatus
            </td>

            <td>
                <a asp-action="UpdateRequest" asp-route-id="@item.Id">Update</a>
            </td>
        </tr>
        }
    </tbody>
</table>

BBS.Web/Areas/Administration/Views/CardRequest/UpdateRequest.cshtml
@model BBS.Web.Models.UpdateRequestViewModel

<head>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }

        th, td {
            padding: 5px;
            text-align: left;
        }
    </style>
</head>
<body>

    <h1 class="d-flex justify-content-center opacity-90 text-muted mt-4">Card request №@Model.CardRequest.Id</h1>


    <div class="row">
        <div class="col-sm-12" style="border: 1px solid black; padding: 10px; margin-bottom: 10px;">
            De luxe Salary Card
        </div>
    </div>

    <table style="width:50%">
        <tr>
            <th>Request Date</th>
            <td>@Model.CardRequest.CreatedAt.ToShortDateString()</td>
        </tr>
        <tr>
            <th>Full Name:</th>
            <td>@Model.CardRequest.User.FirstName @Model.CardRequest.User.LatsName</td>
        </tr>
        <tr>
            <th>Company Name:</th>
            <td>@Model.CardRequest.CompanyName</td>
        </tr>
        <tr>
            <th>City</th>
            <td>@Model.City.Name</td>
        </tr>

        <tr>
            <th>Company Address:</th>
            <td>@Model.CardRequest.CompanyAddress</td>
        </tr>

        <tr>
            <th>Phone:</th>
            <td>@Model.CardRequest.CompanyPhone</td>
        </tr>

    </table>
    <h3></h3>
    <h4>status information</h4>
    @foreach (var item in Model.CardRequestHistories)
    {
        <h4>@item.CreatedAt.ToShortDateString() @item.RequestStatus @item.Comment</h4>
    }
    <h1></h1>
    <input type="text" value="reason" asp-for="CardRequestHistory.Comment" class="form-control" />
    <h1></h1>


    <div class="form-group row">
        <div style="margin-left:3%;">
            <a id="card-accept-btn" asp-action="Accept" asp-controller="CardRequest" asp-route-id="@Model.CardRequest.Id" class="btn btn-dark mr-2 ml-2">Accept</a>
        </div>

        <div style="margin-left:5%;">
            <a id="card-decline-btn" asp-action="Decline" asp-controller="CardRequest" asp-route-id="@Model.CardRequest.Id" class="btn btn-dark mr-2 ml-2">Decline</a>
        </div>

        <div style="margin-left:6%;">
            <a id="card-decline-btn" asp-action="Index"  class="btn btn-dark mr-2 ml-2">Go Back</a>
        </div>
    </div>

</body>