BBS.Web/Models/ChangePasswordViewModel.cs
using BBS.Models.Constants;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BBS.Web.Models
{
    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Old password")]
        public string CurrentPassword { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        [RegularExpression(RegexConstants.RegexForPassword, ErrorMessage = ErrorMessages.InvalidPassword)]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = ErrorMessages.InvalidConfirmPassword)]
        [RegularExpression(RegexConstants.RegexForPassword, ErrorMessage = ErrorMessages.InvalidPassword)]
        public string ConfirmPassword { get; set; }
    }
}

BBS.Web/Models/ForgotPasswordConfirmationViewModel.cs
using BBS.Models.Constants;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BBS.Web.Models
{
    public class ForgotPasswordConfirmationViewModel
    {
        public int UserId { get; set; }
        public string Email { get; set; }

        

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "New Password")]
        [RegularExpression(RegexConstants.RegexForPassword, ErrorMessage ="Password Should contain 1 big letter, 1 small letter, 1 uniqe simbol, 1 number and 8 symbols.")]
       
        public string NewPassword { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name ="Confirm Password")]
        [Compare("NewPassword", ErrorMessage ="Passwordes does not match" )]
        public string ConfirmPassword { get; set; }

        public string Token { get; set; }
    }
}

BBS.Web/Models/ForgotPasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BBS.Models.Constants;

namespace BBS.Web.Models
{
    public class ForgotPasswordViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required(AllowEmptyStrings =false)]
        [RegularExpression( RegexConstants.RegexForPhoneNumber, ErrorMessage = ErrorMessages.InvalidNumber)]
        public string Phone { get; set; }
    }
}

BBS.Web/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace BBS.Web.Models
{
    public class LoginViewModel
    {
        [Required]
        public string PhoneOrEmail { get; set; }

        public string Identifier { get; set; }

        public string PhoneNumber { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

BBS.Web/Models/SecretQuestionConfirmationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BBS.Web.Models
{
    public class SecretQuestionConfirmationViewModel
    {
        public int UserId { get; set; }
        [Required(AllowEmptyStrings = false)]
        public string SecretQuestion { get; set; }

        [Display(Name = "Answer")]
        public string UserAnswer { get; set; }
    }
}

BBS.Web/Controllers/UserAccountController.cs
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BBS.DAL.Constants;
using BBS.Interfaces;
using BBS.Interfaces.Services;
using BBS.Models.Models;
using BBS.Web.Constants;
using BBS.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using LoginViewModel = BBS.Web.Models.LoginViewModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using BBS.Models.Constants;

namespace BBS.Web.Controllers
{	
    [AllowAnonymous]
    public class UserAccountController : Controller
    {
    	private readonly IMailService _mailService;
        private IUserService _userService;
        private ISecurityService _securityService;
        private IQuestionService _questionService;
        private ILogger _logger;
        private readonly SignInManager<User> _signInManager;

		public UserAccountController(IMailService mail, IUserService userService,
            ISecurityService securityService, IQuestionService questionService,
            SignInManager<User> signInManager, ILogger logger)
        {
			_mailService = mail;
            _userService = userService;
            _securityService = securityService;
            _questionService = questionService;
            _logger = logger;
            _signInManager = signInManager;

        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                bool result;
                result = model.Identifier == BankStringConstants.PhoneNumberLogin
                        ? await _securityService.LoginWithPhone(model.PhoneOrEmail, model.Password)
                        : await _securityService.Login(model.PhoneOrEmail, model.Password);

                if (result)
                {
                    User user = model.Identifier == BankStringConstants.PhoneNumberLogin
                        ? await _userService.GetUserByPhone(model.PhoneOrEmail)
                        : await _userService.GetUserByEmail(model.PhoneOrEmail);

                    if (returnUrl != null)
                    {
                        return Redirect(returnUrl);
                    }
                    
                    return Redirect(nameof(RedirectAfterLogin));
                }
                ModelState.AddModelError("", "invalid login attempt");
            }
            return View(model);
        }

        public IActionResult RedirectAfterLogin() 
        {
            return User.IsInRole(Roles.Admin)
                ? RedirectToAction("Index", "CustomLoan", new { area = "Administration" })
                : RedirectToAction("Index", "Cards");
        }

        public IActionResult AddQuestion()
        {
            var questions = _questionService.GetList().GetAwaiter().GetResult().Select(x => x.Content).ToList();

            ViewData["Questions"] = new SelectList(questions);
            return View();
        }

        public IActionResult FirstStepSignUp()
        {
            return View();
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> FirstStepSignUp(SignUpViewModel signUpViewModel)
        {
            if (ModelState.IsValid)
            {
                if (await _userService.GetUserByEmail(signUpViewModel.Email) != null)
                {
                    ModelState.AddModelError("Email", ModelErrors.EmailExists);
                }
                else if (await _userService.GetUserByPhone(signUpViewModel.Phone) != null)
                {
                    ModelState.AddModelError("Phone", ModelErrors.PhoneExists);
                }
                else
                {
                    return RedirectToAction(nameof(SecondStepSignUp), signUpViewModel);
                }
            }
            return View();
        }


        
        public async Task<IActionResult> SecondStepSignUp(SignUpViewModel signUpViewModel)
        {
            SignUpContinuedViewModel signUpContinuedViewModel = new SignUpContinuedViewModel
            {
                FirstName = signUpViewModel.FirstName,
                LatsName = signUpViewModel.LatsName,
                Phone = signUpViewModel.Phone,
                Email = signUpViewModel.Email
            };

            var cities = await _userService.GetUserCities();
            ViewData["Cities"] = cities;
            var questions = await _questionService.GetList();
            ViewData["Questions"] = questions;
            return View(signUpContinuedViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> SecondStepSignUp(SignUpContinuedViewModel signUpContinuedViewModel)
        {
            if (ModelState.IsValid)
            {
                

                User tempUser = await _userService.GetUserByPassportId(signUpContinuedViewModel.PassportId);
                if (tempUser != null)
                {
                    ModelState.AddModelError("PassportId", ModelErrors.PassportIdExists);
                }
                else
                {
                    User user = signUpContinuedViewModel;
                    User createdUser = await _userService.CreateUser(user, signUpContinuedViewModel.Password);

                    if (createdUser != null)
                    {
                        var role = createdUser.FirstName.Contains(Roles.Admin) ? Roles.Admin : Roles.User;
                        await _userService.AddRole(createdUser, role);
                        await _userService.AddClaim(createdUser, new Claim(ClaimTypes.Name, createdUser.FirstName));
                        await _userService.GenerateCard(createdUser);

	        			await _mailService.SignupWelcome(user.Email, user.FirstName+" "+user.LatsName);
                        return RedirectToAction(nameof(Login));
                    }
                }
            }

            var cities = await _userService.GetUserCities();
            ViewData["Cities"] = cities;
            var questions = await _questionService.GetList();
            ViewData["Questions"] = questions;
            return View();
        }
        
          

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _securityService.Logout();

            return RedirectToAction(nameof(Login));
        }

        public async Task<IActionResult> Update()
        {
            User currentUser = await _userService.GetCurrentUser(User);
            if (currentUser.FirstName.Contains(Roles.Admin))
            {
                return NotFound();
            }
            User userIncludingAccounts = await _userService.GetById(currentUser.Id);

            if (userIncludingAccounts == null)
            {
                return NotFound();
            }

            ViewData["Questions"] = await _questionService.GetList();


            return View(userIncludingAccounts);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(User user)
        {
            User currentUser = await _userService.GetCurrentUser(User);
            user.Id = currentUser.Id;

            if (ModelState.IsValid)
            {
                try
                {
                    await _userService.Update(user);
                }
                catch (DbUpdateConcurrencyException)
                {
                    bool exists = await _userService.UserExists(user.Id);
                    if (!exists)
                    {
                        return NotFound();
                    }
                }
                TempData["SuccessMessage"] = Messages.SuccessMessage;
                return RedirectToAction(nameof(Update));
            }
            return View(user);
        }

        public IActionResult ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ForgotPassword(ForgotPasswordViewModel model)
        {
            User user = await _userService.GetByEmail(model.Email);
            if (user == null)
            {
                ModelState.AddModelError("Email", "User with this email is not registered!");
                return View();
            }
            else if (model.Phone != user.Phone)
            {
                ModelState.AddModelError("Phone", "Incorrect Phone number!");
                return View();
            }
            ForgotPasswordSecondStepViewModel forgotPasswordSecondStepViewModel = new ForgotPasswordSecondStepViewModel() { Email = user.Email };
            return RedirectToAction(nameof(SecretQuestionConfirmation), forgotPasswordSecondStepViewModel);
        }

        public async Task<IActionResult> SecretQuestionConfirmation(ForgotPasswordSecondStepViewModel model)
        {
            User user = await _userService.GetByEmail(model.Email);
            ViewData["Question"] = user.Question;
            SecretQuestionConfirmationViewModel secretQuestionConfirmationViewModel = new SecretQuestionConfirmationViewModel() { UserId = user.Id };
            return View(secretQuestionConfirmationViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> SecretQuestionConfirmation(SecretQuestionConfirmationViewModel model)
        {
            User user = await _userService.GetById(model.UserId);
            if (user.Answer != model.UserAnswer)
            {

BBS.Web/Views/UserAccount/AccessDenied.cshtml
@{
    ViewData["Title"] = "AccessDenied";
}

<center><div class="alert alert-danger">You are not authorized to access this page.</div></center>

BBS.Web/Views/UserAccount/AddQuestion.cshtml
@{
    ViewData["Title"] = "Order";
}

<div class="container">
    <h1 class="text-center">Profile and Settings</h1>
    <form class="card p-2">
        <div class="form-group row">
            <label for="newquestion" class="col-sm-2 col-form-label"> Add new question</label>
            <div class="col-sm-auto">

            </div>
        </div>


        <div class="form-group row">
            <div class="col-sm-auto">
                    <select id="DeffaultAccount" class="form-control" asp-items="ViewBag.Questions"></select>
            </div>
        </div>

        <div class="form-group row">
            <label for="Answer" class="col-sm-2 col-form-label">Answer</label>
            <div class="col-sm-auto">

            </div>
        </div>

        <div class="form-group row">

            <div class="col-sm-auto">
                <input type="text" class="form-control" id="answer" placeholder="">
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-10">
                <input type="submit" id="addquestion" value="Add" >
            </div>
        </div>







     



    </form>
   
</div>

BBS.Web/Views/UserAccount/ChangePassword.cshtml
@model ChangePasswordViewModel

<h2>Change Password</h2>
<hr />
<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CurrentPassword"></label>
                <input asp-for="CurrentPassword" class="form-control" />
                <span asp-validation-for="CurrentPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NewPassword"></label>
                <input asp-for="NewPassword" class="form-control" />
                <span asp-validation-for="NewPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <button type="submit" class="btn btn-primary">Update</button>
                <a class="btn btn-secondary" asp-action="Update" asp-controller="UserAccount">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BBS.Web/Views/UserAccount/FirstStepSignUp.cshtml
@model BBS.Web.Models.SignUpViewModel

@{
    ViewData["Title"] = "FirstStepSignUp";
}

<div class="row">
    <div style="line-height: 5px; margin-top:3%; padding-left:15px;">
        <p style="font-size:large;">Academy bank is the largest commercial bank in Georgia, in terms of the number of clients,</p>
        <p style="font-size:large;">assets value, loan portfolio and taxes paid to the national budget.</p>
    </div>
    <div class="col-sm-6" style="margin-top:2%;">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2978.049143706828!2d44.70786511573412!3d41.71945838330539!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40447377897e79d7%3A0x4e4ac031e18af6e!2zMTAg4YOQ4YOc4YOQIOGDnuGDneGDmuGDmOGDouGDmeGDneGDleGDoeGDmeGDkOGDmOGDkOGDoSDhg6Xhg6Phg6nhg5AsIOGDl-GDkeGDmOGDmuGDmOGDoeGDmA!5e0!3m2!1ska!2sge!4v1579711167072!5m2!1ska!2sge" frameborder="0" style="border:0; width:100%; height:100%;" allowfullscreen=""></iframe>
    </div>

    <div>
        <form asp-action="FirstStepSignUp">
            <div style="margin-top:5%; margin-top:9%; margin-bottom:6.5%;">
                <h3>Sign Up</h3>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label asp-for="FirstName" style="font-size: large;">First Name</label>
                </div>
                <div class="form-group col-sm-6">
                    <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label asp-for="LatsName" style="font-size: large;" class="control-label">Last Name</label>
                </div>
                <div class="form-group col-sm-6">
                    <input asp-for="LatsName" class="form-control" />
                    <span asp-validation-for="LatsName" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label asp-for="Phone" style="font-size: large;" class="control-label">Phone number</label>
                </div>
                <div class="form-group col-sm-6">
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label asp-for="Email" style="font-size: large;" class="control-label">Email</label>
                </div>
                <div class="form-group col-sm-6">
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div style="margin-left:4%;">
                    <a style="padding-left:50px; padding-right:50px;" class="btn btn-secondary" asp-action="Index" asp-controller="Home">Return</a>
                </div>
                <div style="margin-left:10%;">
                    <input type="submit" value="Continue" class="btn btn-primary" style="padding-left:44px; padding-right:44px;" />
                </div>
            </div>
        </form>
    </div>
</div>

BBS.Web/Views/UserAccount/ForgotPassword.cshtml
@model ForgotPasswordViewModel

<div class="raw">
    <div class="col-md-12">
        <form method="post">

            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"> </span>
                <div>

                </div>
                <label asp-for="Phone"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"> </span>

            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-secondary" />
                <a asp-action="Login" class="btn btn-secondary"> Cancel</a>
            </div>       
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BBS.Web/Views/UserAccount/SecondStepSignUp.cshtml
@using BBS.Models.Models
@model BBS.Web.Models.SignUpContinuedViewModel

@{
    ViewData["Title"] = "SecondStepSignUp";
}

<div>
    <div>
        <h1 style="margin-bottom: 2%; margin-top: 2%;">Please, put your personal data to complete registration</h1>
    </div>
    <form asp-action="SecondStepSignUp">

        <div class="form-group" hidden>
            <label asp-for="FirstName" class="control-label"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="form-group" hidden>
            <label asp-for="LatsName" class="control-label"></label>
            <input asp-for="LatsName" class="form-control" />
            <span asp-validation-for="LatsName" class="text-danger"></span>
        </div>
        <div class="form-group" hidden>
            <label asp-for="Phone" class="control-label"></label>
            <input asp-for="Phone" class="form-control" />
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>
        <div class="form-group" hidden>
            <label asp-for="Email" class="control-label"></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>


        <div class="row">
            <div class="col-sm-3">
                <label style="font-size: large;">Sex</label>
            </div>
            <div class="form-group col-sm-6">
                <div class="row" style="padding-left:4% !important;">
                    <div class="col-sm-3">
                        <label class="form-check-label">
                            <input type="radio" value="true" class="form-check-input" asp-for="Sex" />Male
                        </label>
                    </div>
                    <div class="col-sm-3">
                        <label class="form-check-label">
                            <input type="radio" value="false" class="form-check-input" asp-for="Sex" />Female
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <label asp-for="PassportId" class="control-label" style="font-size: large;">Passport ID</label>
            </div>
            <div class="form-group col-sm-3">
                <input asp-for="PassportId" class="form-control" />
                <span asp-validation-for="PassportId" class="text-danger"></span>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3">
                <label asp-for="CityId" class="control-label" style="font-size: large;">City</label>
            </div>
            <div class="col-sm-3" style="margin-bottom:1%;">
                <select asp-for="CityId" class="form-control">
                    @foreach (var item in ViewData["Cities"] as List<City>)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                </select>
                <span asp-validation-for="CityId" class="text-danger"></span>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3">
                <label asp-for="Address" class="control-label" style="font-size: large;">Address</label>
            </div>
            <div class="form-group col-sm-3">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3">
                <label asp-for="QuestionId" class="control-label" style="font-size: large;" style="font-size: large;">Select question</label>
            </div>

            <div class="col-sm-3" style="margin-bottom:1%;">
                <select asp-for="QuestionId" class="form-control">
                    @foreach (var item in ViewData["Questions"] as List<Question>)
                    {
                        <option value="@item.Id">@item.Content</option>
                    }
                </select>
                <span asp-validation-for="QuestionId" class="text-danger"></span>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3">
                <label asp-for="Answer" class="control-label" style="font-size: large;">Answer</label>
            </div>
            <div class="form-group col-sm-3">
                <input asp-for="Answer" class="form-control" />
                <span asp-validation-for="Answer" class="text-danger"></span>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3">
                <label asp-for="Password" class="control-label" style="font-size: large;">Password</label>
            </div>
            <div class="form-group col-sm-3">
                <input asp-for="Password" class="form-control" data-toggle="password" id="passwordInput" />
                <input type="checkbox" onclick="myFunction()"> Show Password
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>

        <div>
            <p style="font-size:large;">By clicking Sign Up, you agree to our Terms, Data Policy and Cookies Policy.</p>
        </div>

        <div class="form-group row">
            <div style="margin-left:25%;">
                <a style="padding-left:50px; padding-right:50px;" class="btn btn-secondary" asp-action="FirstStepSignUp" asp-controller="UserAccount">Return</a>
            </div>
            <div style="margin-left:1%;">
                <input type="submit" value="Sign Up" class="btn btn-primary" style="padding-left:44px; padding-right:44px;" />
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script src="~/js/showPassword.js"></script>

BBS.Web/Views/UserAccount/Update.cshtml
@using BBS.Models.Models
@model BBS.Models.Models.User

@{
    ViewData["Title"] = "Update";
}

<div class="container">
    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success" role="alert">
            @TempData["SuccessMessage"]
        </div>
    }
    <h1 class="text-center text-muted mt-3 mb-3">Profile Settings</h1>
    <form class="card content-card pl-4 p-3" asp-action="Update">
        <div class="form-group row">
            <label asp-for="FirstName" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-auto">
                <input asp-for="FirstName" class="form-control" placeholder="@Model.FirstName" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>


        <div class="form-group row">
            <label asp-for="PassportId" class="col-sm-2 col-form-label">Passport ID</label>
            <div class="col-sm-auto">
                <p class=" col-form-label" id="name">@Model.PassportId</p>
                <input asp-for="PassportId" class="form-control" value="@Model.PassportId" hidden />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Phone" class="col-sm-2 col-form-label">Mobile number</label>
            <div class="col-sm-auto">
                <input asp-for="Phone" class="form-control" placeholder="@Model.Phone" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>


        <div class="form-group row">
            <label asp-for="Email" class="col-sm-2 col-form-label">Email</label>
            <div class="col-sm-4">
                <input asp-for="Email" class="form-control" placeholder="@Model.Email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>



        <div class="form-group row">
            <label asp-for="DefaultAccountId" class="col-sm-2 col-form-label">Deffault Account</label>
            <div class="col-sm-4">
                <select class="form-control custom-select">

                    @foreach (var item in Model.Accounts as IEnumerable<Account>)
                    {
                        <option value="@item.Id">@item.Number</option>
                    }
                </select>
                <span asp-validation-for="DefaultAccountId" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="AllowPhoneForLogin" class="col-sm-4 col-form-label">Allow to use phone number as login</label>
            <div class="col-sm-auto" style="margin-top:0.8%;">
                <input type="checkbox" asp-for="AllowPhoneForLogin" value="true" class="form-check-input" />
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-10">
                <label asp-for="QuestionId" class="col-form-label"><b>Security Questions</b></label>
            </div>
            <div class="col-sm-6">
                <select asp-for="QuestionId" class="form-control">
                    @foreach (var item in ViewData["Questions"] as IEnumerable<Question>)
                    {
                        @if (Model.QuestionId == item.Id)
                        {
                            <option value="@item.Id" selected>@item.Content</option>
                        }
                        else
                        {
                            <option value="@item.Id">@item.Content</option>
                        }
                    }
                </select>
                <span asp-validation-for="QuestionId" class="text-danger"></span>
            </div>
            <div class="col-sm-auto">
                <input type="text" asp-for="Answer" class="form-control" placeholder="@Model.Answer" />
                <span asp-validation-for="Answer" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-10">
                <a class="btn btn-secondary" id="ChangePassword" asp-controller="UserAccount" asp-action="ChangePassword">Change Password</a>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-2 ml-auto mt-2">
            </div>
            <div class="col-sm-2 ml-auto mt-2 d-flex">
                <a asp-action="Index" asp-controller="Home" class="ml-auto btn btn-primary">Return</a>
                <input  type="submit" value="Save" class="ml-auto btn btn-success">
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}