BBS.Web/Areas/Administration/Controllers/LoanTypeManagmentController.cs
using BBS.Interfaces.Services;
using BBS.Models.Models;
using BBS.Web.Areas.Administration.Constants;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;

namespace BBS.Web.Controllers
{
    [Area(AdministratorArea.Name)]
    [Authorize(Policy = AdministratorArea.Policy)]
    public class LoanTypeManagmentController : Controller
    {
        private readonly ILoanTypeService _loanTypeService;
        private readonly ICurrencyService _currencyService;

        public LoanTypeManagmentController(ILoanTypeService loanTypeService, ICurrencyService currencyService)
        {
            _loanTypeService = loanTypeService;
            _currencyService = currencyService;
        }


        public async Task<IActionResult> Index()
        {
            return View(await _loanTypeService.GetLoanTypes());
        }


        public async Task<IActionResult> Details(int id)
        {
            var loanType = await _loanTypeService.GetLoanType(id);

            if (loanType == null)
            {
                return NotFound();
            }

            return View(loanType);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewData["CurrencyId"] = new SelectList(await _currencyService.GetAll(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,GeneralInformation,MinLoanSum,MaxLoanSum,InterestRate,LoanSummary,MonthlyFee,MinTerm,MaxTerm,PaymentForAccidentInsurance,FeeForInsuranceLoan,FreeForServicesUponReciptCash,CurrencyId")] LoanType loanType)
        {
            if (ModelState.IsValid)
            {
                await _loanTypeService.AddLoan(loanType);
                return RedirectToAction(nameof(Index));
            }


            ViewData["CurrencyId"] = new SelectList(await _currencyService.GetAll(), "Id", "Name");
            return View(loanType);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var loanType = await _loanTypeService.GetLoanType(id);
            if (loanType == null)
            {
                return NotFound();
            }
            ViewData["CurrencyId"] = new SelectList(await _currencyService.GetAll(), "Id", "Name");
            return View(loanType);
        }

        [HttpPost]
        public async Task<IActionResult> Update([Bind("Id,Name,Description,GeneralInformation,MinLoanSum,MaxLoanSum,InterestRate,LoanSummary,MonthlyFee,MinTerm,MaxTerm,PaymentForAccidentInsurance,FeeForInsuranceLoan,FreeForServicesUponReciptCash,CurrencyId")] LoanType loanType)
        {
            if (ModelState.IsValid)
            {
                await _loanTypeService.UpdateLoanType(loanType);

                return RedirectToAction(nameof(Index));
            }

            ViewData["CurrencyId"] = new SelectList(await _currencyService.GetAll(), "Id", "Name");
            return View(loanType);
        }


        public async Task<IActionResult> Delete(int id)
        {
            var loanType = await _loanTypeService.GetLoanType(id);

            if (loanType == null)
            {
                return NotFound();
            }

            return View(loanType);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _loanTypeService.DeleteLoanType(id);
            return RedirectToAction(nameof(Index));

        }

    }
}

BBS.Web/Areas/Administration/Views/LoanTypeManagment/Create.cshtml
@model BBS.Models.Models.LoanType
@{
    ViewData["Title"] = "Add New Loan Type";
}

<h1 class="text-center mt-3 mb-3">Add New Loan Type</h1>


<form class="border border-info rounded" asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row p-3">
        <div class="col-6 col-md-6 col-sm-6 left">
            <div class="form-group row mb-3">
                <label asp-for="Name" class="control-label col-sm-4"></label>
                <input asp-for="Name" class="form-control col-sm-8" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="Description" class="control-label col-sm-4"></label>
                <textarea asp-for="Description" class="form-control col-sm-8"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="GeneralInformation" class="control-label col-sm-4"></label>
                <textarea asp-for="GeneralInformation" class="form-control col-sm-8"></textarea>
                <span asp-validation-for="GeneralInformation" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="MinLoanSum" class="control-label col-sm-4"></label>
                <input asp-for="MinLoanSum" class="form-control col-sm-8" />
                <span asp-validation-for="MinLoanSum" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="MaxLoanSum" class="control-label col-sm-4"></label>
                <input asp-for="MaxLoanSum" class="form-control col-sm-8" />
                <span asp-validation-for="MaxLoanSum" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="MonthlyFee" class="control-label col-sm-4"></label>
                <input asp-for="MonthlyFee" class="form-control col-sm-8" />
                <span asp-validation-for="MonthlyFee" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="CurrencyId" class="control-label col-sm-4"></label>
                <select asp-for="CurrencyId" class="form-control col-sm-8 custom-select" asp-items="ViewBag.CurrencyId">
                    <option selected>Select One</option>
                </select>
                <span asp-validation-for="CurrencyId" class="text-danger"></span>
            </div>

        </div>

        <div class="col-6 col-md-6 col-sm-6">
            <div class="form-row mb-3">
                <label asp-for="InterestRate" class="control-label col-sm-4"></label>
                <input asp-for="InterestRate" class="form-control col-sm-8" />
                <span asp-validation-for="InterestRate" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="PaymentForAccidentInsurance" class="control-label col-sm-4"></label>
                <input asp-for="PaymentForAccidentInsurance" class="form-control col-sm-8" />
                <span asp-validation-for="PaymentForAccidentInsurance" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="MinTerm" class="control-label col-sm-4"></label>
                <input asp-for="MinTerm" class="form-control col-sm-8" />
                <span asp-validation-for="MinTerm" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="MaxTerm" class="control-label col-sm-4"></label>
                <input asp-for="MaxTerm" class="form-control col-sm-8" />
                <span asp-validation-for="MaxTerm" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="FeeForInsuranceLoan" class="control-label col-sm-4"></label>
                <input asp-for="FeeForInsuranceLoan" class="form-control col-sm-8" />
                <span asp-validation-for="FeeForInsuranceLoan" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="FreeForServicesUponReciptCash" class="control-label col-sm-4"></label>
                <input asp-for="FreeForServicesUponReciptCash" class="form-control col-sm-8" />
                <span asp-validation-for="FreeForServicesUponReciptCash" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="LoanSummary" class="control-label col-sm-4"></label>
                <textarea asp-for="LoanSummary" class="form-control col-sm-8"></textarea>
                <span asp-validation-for="LoanSummary" class="text-danger"></span>
            </div>

        </div>
    </div>
    <div class="row">
        <a class="btn btn-dark ml-auto mb-3" asp-controller="LoanTypeManagment" asp-action="Index">Cancel</a>
        <input type="submit" value="Submit" class="btn btn-secondary ml-2 mr-4 mb-3"/>
    </div>
</form>

BBS.Web/Areas/Administration/Views/LoanTypeManagment/Delete.cshtml
@model BBS.Models.Models.LoanType
@{
    ViewData["Title"] = "Delete Loan Type";
}

<h1 class="text-center text-secondary mt-3 mb-3">Delete Loan Type</h1>

<div class="container border border-info rounded">
    <dl class="row m-2">
        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.GeneralInformation)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.GeneralInformation)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.MinLoanSum)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.MinLoanSum)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.MaxLoanSum)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.MaxLoanSum)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.InterestRate)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.InterestRate)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.Currency.Name)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.Currency.Name)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.LoanSummary)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.LoanSummary)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.MonthlyFee)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.MonthlyFee)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.MinTerm)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.MinTerm)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.MaxTerm)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.MaxTerm)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.PaymentForAccidentInsurance)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.PaymentForAccidentInsurance)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.FeeForInsuranceLoan)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.FeeForInsuranceLoan)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.FreeForServicesUponReciptCash)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.FreeForServicesUponReciptCash)
        </dd>
    </dl>
    <form asp-action="Delete" class="row mb-3">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-secondary ml-auto mr-3" />
        <a asp-action="Index" class="btn btn-dark mr-3">Back</a>
    </form>
</div>

BBS.Web/Areas/Administration/Views/LoanTypeManagment/Details.cshtml
@model BBS.Models.Models.LoanType
@{
    ViewData["Title"] = "Loan Type Details";
}

<h1 class="text-center text-muted">Loan Type Details</h1>

<div class="container border border-info rounded">
    <dl class="row m-2">
        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.GeneralInformation)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.GeneralInformation)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.MinLoanSum)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.MinLoanSum)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.MaxLoanSum)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.MaxLoanSum)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.InterestRate)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.InterestRate)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.Currency.Name)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.Currency.Name)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.LoanSummary)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.LoanSummary)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.MonthlyFee)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.MonthlyFee)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.MinTerm)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.MinTerm)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.MaxTerm)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.MaxTerm)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.PaymentForAccidentInsurance)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.PaymentForAccidentInsurance)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.FeeForInsuranceLoan)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.FeeForInsuranceLoan)
        </dd>

        <dt class="col-sm-6">
            @Html.DisplayNameFor(model => model.FreeForServicesUponReciptCash)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.FreeForServicesUponReciptCash)
        </dd>
    </dl>
    <div class="row mb-3">
        @if (!Model.LoanRequests.Any(x => x.Loan != null && x.Loan.Status == "Active"))
        {
            <a asp-area="Administration" asp-controller="LoanTypeManagment" asp-action="Update" asp-route-id="@Model.Id" class="btn btn-secondary ml-auto mr-3">Edit</a>
        }
        <a asp-area="Administration" asp-controller="LoanTypeManagment" asp-action="Index" class="btn btn-dark mr-3">Back</a>
    </div>
</div>

BBS.Web/Areas/Administration/Views/LoanTypeManagment/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using BBS.Models.Models
@using BBS.Web.Areas.Administration.Constants
@model IEnumerable<BBS.Models.Models.LoanType>
@{
    ViewData["Title"] = "Loan Types";
}

<h1 class="d-flex justify-content-center opacity-90 text-muted mt-4">Loan Managment</h1>

<table class="table table-bordered table-responsive text-nowrap">
    <thead class="thead-dark">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Description)</th>
            <th>@Html.DisplayNameFor(model => model.GeneralInformation)</th>
            <th>@Html.DisplayNameFor(model => model.MinLoanSum)</th>
            <th>@Html.DisplayNameFor(model => model.MaxLoanSum)</th>
            <th>@Html.DisplayNameFor(model => model.InterestRate)</th>
            <th>@Html.DisplayNameFor(model => model.Currency.Name)</th>
            <th>@Html.DisplayNameFor(model => model.LoanSummary)</th>
            <th>@Html.DisplayNameFor(model => model.MonthlyFee)</th>
            <th>@Html.DisplayNameFor(model => model.MinTerm)</th>
            <th>@Html.DisplayNameFor(model => model.MaxTerm)</th>
            <th>@Html.DisplayNameFor(model => model.PaymentForAccidentInsurance)</th>
            <th>@Html.DisplayNameFor(model => model.FeeForInsuranceLoan)</th>
            <th>@Html.DisplayNameFor(model => model.FreeForServicesUponReciptCash)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Description)</td>
                <td>@Html.DisplayFor(modelItem => item.GeneralInformation)</td>
                <td>@Html.DisplayFor(modelItem => item.MinLoanSum)</td>
                <td>@Html.DisplayFor(modelItem => item.MaxLoanSum)</td>
                <td>@Html.DisplayFor(modelItem => item.InterestRate)</td>
                <td>@Html.DisplayFor(modelItem => item.Currency.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.LoanSummary)</td>
                <td>@Html.DisplayFor(modelItem => item.MonthlyFee)</td>
                <td>@Html.DisplayFor(modelItem => item.MinTerm)</td>
                <td>@Html.DisplayFor(modelItem => item.MaxTerm)</td>
                <td>@Html.DisplayFor(modelItem => item.PaymentForAccidentInsurance)</td>
                <td>@Html.DisplayFor(modelItem => item.FeeForInsuranceLoan)</td>
                <td>@Html.DisplayFor(modelItem => item.FreeForServicesUponReciptCash)</td>
                <td>
                    @{ var hasLoan = item.LoanRequests.Any(x => x.Loan != null && x.Loan.Status == AdministratorArea.ActiveLoanStatus);}
                    <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id">Details</a>
                    @if (User.IsInRole("Admin") && !hasLoan)
                    {
                        <a class="btn btn-dark" asp-action="Update" asp-route-id="@item.Id">Update</a>
                        <a class="btn btn-dark" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="row">
    <a class="btn btn-secondary ml-auto mr-3" asp-action="Create">Add New Loan Type</a>
</div>

BBS.Web/Areas/Administration/Views/LoanTypeManagment/Update.cshtml
@model BBS.Models.Models.LoanType
@{
    ViewData["Title"] = "Update Loan Type";
}

<h1 class="text-center mt-3 mb-3">Update Loan Type</h1>


<form class="border border-info rounded" asp-action="Update">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row p-3">
        <div class="col-6 col-md-6 col-sm-6 left">
            <!-- For Name -->
            <div class="form-row mb-3">
                <label asp-for="Name" class="control-label col-sm-4"></label>
                <input asp-for="Name" class="form-control col-sm-8" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="Description" class="control-label col-sm-4"></label>
                <textarea asp-for="Description" class="form-control col-sm-8"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="GeneralInformation" class="control-label col-sm-4"></label>
                <textarea asp-for="GeneralInformation" class="form-control col-sm-8"></textarea>
                <span asp-validation-for="GeneralInformation" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="MinLoanSum" class="control-label col-sm-4"></label>
                <input asp-for="MinLoanSum" class="form-control col-sm-8" />
                <span asp-validation-for="MinLoanSum" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="MaxLoanSum" class="control-label col-sm-4"></label>
                <input asp-for="MaxLoanSum" class="form-control col-sm-8" />
                <span asp-validation-for="MaxLoanSum" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="MonthlyFee" class="control-label col-sm-4"></label>
                <input asp-for="MonthlyFee" class="form-control col-sm-8" />
                <span asp-validation-for="MonthlyFee" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="CurrencyId" class="control-label col-sm-4"></label>
                <select asp-for="CurrencyId" class="form-control col-sm-8 custom-select" asp-items="ViewBag.CurrencyId">
                    <option selected>Select One</option>
                </select>
                <span asp-validation-for="CurrencyId" class="text-danger"></span>
            </div>

        </div>

        <div class="col-6 col-md-6 col-sm-6">
            <div class="form-row mb-3">
                <label asp-for="InterestRate" class="control-label col-sm-4"></label>
                <input asp-for="InterestRate" class="form-control col-sm-8" />
                <span asp-validation-for="InterestRate" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="PaymentForAccidentInsurance" class="control-label col-sm-4"></label>
                <input asp-for="PaymentForAccidentInsurance" class="form-control col-sm-8" />
                <span asp-validation-for="PaymentForAccidentInsurance" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="MinTerm" class="control-label col-sm-4"></label>
                <input asp-for="MinTerm" class="form-control col-sm-8" />
                <span asp-validation-for="MinTerm" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="MaxTerm" class="control-label col-sm-4"></label>
                <input asp-for="MaxTerm" class="form-control col-sm-8" />
                <span asp-validation-for="MaxTerm" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="FeeForInsuranceLoan" class="control-label col-sm-4"></label>
                <input asp-for="FeeForInsuranceLoan" class="form-control col-sm-8" />
                <span asp-validation-for="FeeForInsuranceLoan" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="FreeForServicesUponReciptCash" class="control-label col-sm-4"></label>
                <input asp-for="FreeForServicesUponReciptCash" class="form-control col-sm-8" />
                <span asp-validation-for="FreeForServicesUponReciptCash" class="text-danger"></span>
            </div>

            <div class="form-row mb-3">
                <label asp-for="LoanSummary" class="control-label col-sm-4"></label>
                <textarea asp-for="LoanSummary" class="form-control col-sm-8"></textarea>
                <span asp-validation-for="LoanSummary" class="text-danger"></span>
            </div>

        </div>
    </div>
    <div class="row">
        <a class="btn btn-dark ml-auto mb-3" asp-controller="LoanTypeManagment" asp-action="Index">Cancel</a>
        <input type="submit" value="Submit" class="btn btn-secondary ml-2 mr-4 mb-3" />
    </div>
</form>